# Generated by Django 5.0.14 on 2026-09-19 17:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, help_text='Залиште порожнім для категорії верхнього рівня.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивні товари не показуються в каталозі та пошуку.', verbose_name='Активний')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок на складі')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='products_pr_is_acti_1cd666_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx')],
            },
        ),
    ]
