# Generated by Django 5.0.14 on 2026-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою (мок)'), ('cash_on_delivery', 'Оплата при отриманні')], default='card', max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
